# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
        inputs:
            pull-latest:
                required: false
                type: boolean
                default: false
            is-production:
                required: true
                type: boolean
                default: true
    workflow_call:
        inputs:
            pull-latest:
                required: false
                type: boolean
                default: false
            is-production:
                required: true
                type: boolean
                default: true
        secrets:
            VERCEL_TOKEN:
                description: "vercel token"
                required: true
            VERCEL_ORG_ID:
                description: "vercel organization id"
                required: true
            VERCEL_PROJECT_ID:
                description: "vercel project id"
                required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Pull latest
              if: ${{ inputs.pull-latest }}
              run: git pull

            - name: Install package
              run: yarn install

            - name: Deploy Preview
              if: ${{ !inputs.is-production }}
              run: VERCEL_ORG_ID=$VERCEL_ORG_ID VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID yarn dlx vercel --token $VERCEL_TOKEN > deployment.txt
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

            - name: Comment preview url
              if: ${{ !inputs.is-production }}
              uses: thollander/actions-comment-pull-request@v2
              with:
                  filePath: deployment.txt
                  reactions: rocket

            - name: Deploy Production
              if: ${{ inputs.is-production }}
              run: VERCEL_ORG_ID=$VERCEL_ORG_ID VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID yarn dlx vercel --prod --token $VERCEL_TOKEN
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
