# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    workflow_call:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.3.0
              with:
                  node-version: "16"

            - name: Install package
              run: yarn install

            - name: Deploy
              run: yarn vercel --prod --token $VERCEL_TOKEN
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
