# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the workflow will run
on:
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:
    workflow_call:
        inputs:
            pull-latest:
                required: false
                type: boolean
                default: false
        secrets:
            VERCEL_TOKEN:
                description: "vercel token"
                required: true
            VERCEL_ORG_ID:
                description: "vercel organization id"
                required: true
            VERCEL_PROJECT_ID:
                description: "vercel project id"
                required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js environment
              uses: actions/setup-node@v2.3.0
              with:
                  node-version: "16"

            - name: Pull latest
              if: ${{ inputs.pull-latest }}
              run: git pull

            - name: Install package
              run: yarn install

            - name: Deploy
              run: VERCEL_ORG_ID=$VERCEL_ORG_ID VERCEL_PROJECT_ID=$VERCEL_PROJECT_ID yarn vercel --prod --scope oat9002 --token $VERCEL_TOKEN
              env:
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
