# This is a basic workflow to help you get started with Actions

name: deploy-preview

# Controls when the workflow will run
on:
    issue_comment:
        types: [created, edited]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # release workflow contains a single job called "build"
    deploy:
        if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/deploy') }}
        uses: ./.github/workflows/deploy.yml
        with:
            pull-latest: true
        secrets:
            IS_PRODUCTION: false
            VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
