# This is a basic workflow to help you get started with Actions

name: pull_request

on:
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    build_and_test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js environment
              uses: actions/setup-node@v4
              with:
                  node-version: 26

            - name: Install package
              run: |
                  node --version
                  yarn --version
                  yarn install --immutable

            - name: Build
              run: yarn build

            - name: Test
              run: yarn test --runInBand --ci --forceExit
